app = "rmp-discord-bot"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    path = "/"
